import { FemaleAvatar, MaleAvatar, Skills } from "../types/interfaces";

export const SkillsImage: Skills = {
  nextjs: "/skills/nextjs.png",
  figma: "/skills/figma.png",
  express: "/skills/express.png",
  js: "/skills/js.png",
  mern: "/skills/mern.png",
  mongodb: "/skills/mongodb.png",
  node: "/skills/node.png",
  react: "/skills/react.png",
  reactnative: "/skills/reactnative.png",
  sketch: "/skills/sketch.png",
  wp: "/skills/wp.png",
  xd: "/skills/xd.png",
  java: "/skills/java.png",
  python: "/skills/python.png",
};
export const MaleImage: MaleAvatar = {
  1: "/maleAvatar/1.png",
  2: "/maleAvatar/2.png",
  3: "/maleAvatar/3.png",
  4: "/maleAvatar/4.png",
  5: "/maleAvatar/5.png",
  6: "/maleAvatar/6.png",
  7: "/maleAvatar/7.png",
  8: "/maleAvatar/8.png",
  9: "/maleAvatar/9.png",
  10: "/maleAvatar/10.png",
  11: "/maleAvatar/11.png",
  12: "/maleAvatar/12.png",
  13: "/maleAvatar/13.png",
  14: "/maleAvatar/14.png",
  15: "/maleAvatar/15.png",
  16: "/maleAvatar/16.png",
  17: "/maleAvatar/17.png",
  18: "/maleAvatar/18.png",
  19: "/maleAvatar/19.png",
  20: "/maleAvatar/20.png",
  21: "/maleAvatar/21.png",
  22: "/maleAvatar/22.png",
  23: "/maleAvatar/23.png",
  24: "/maleAvatar/24.png",
  25: "/maleAvatar/25.png",
  26: "/maleAvatar/26.png",
  27: "/maleAvatar/27.png",
  28: "/maleAvatar/28.png",
};
export const FemaleImage: FemaleAvatar = {
  1: "/femaleAvatar/1.png",
  2: "/femaleAvatar/2.png",
  3: "/femaleAvatar/3.png",
  4: "/femaleAvatar/4.png",
  5: "/femaleAvatar/5.png",
  6: "/femaleAvatar/6.png",
  7: "/femaleAvatar/7.png",
  8: "/femaleAvatar/8.png",
  9: "/femaleAvatar/9.png",
  10: "/femaleAvatar/10.png",
  11: "/femaleAvatar/11.png",
  12: "/femaleAvatar/12.png",
  13: "/femaleAvatar/13.png",
  14: "/femaleAvatar/14.png",
  15: "/femaleAvatar/15.png",
  16: "/femaleAvatar/16.png",
  17: "/femaleAvatar/17.png",
  18: "/femaleAvatar/18.png",
  19: "/femaleAvatar/19.png",
  20: "/femaleAvatar/20.png",
  21: "/femaleAvatar/21.png",
  22: "/femaleAvatar/22.png",
  23: "/femaleAvatar/23.png",
  24: "/femaleAvatar/24.png",
  25: "/femaleAvatar/25.png",
  26: "/femaleAvatar/26.png",
  27: "/femaleAvatar/27.png",
  28: "/femaleAvatar/28.png",
  29: "/femaleAvatar/29.png",
  30: "/femaleAvatar/30.png",
  31: "/femaleAvatar/31.png",
  32: "/femaleAvatar/32.png",
  33: "/femaleAvatar/33.png",
  34: "/femaleAvatar/34.png",
};
